## Numpy Exercises - Part 1

In [1]:
import numpy as np

In [4]:
print(np.__version__)
#np.show_config()

1.19.5


In [5]:
Z = np.zeros(10)
print (Z)

#creates a null vector of size 10

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
Z = np.zeros((69,420))
print ("%d bytes" % (Z.size * Z.itemsize))

#find memory size of a defined array

231840 bytes


In [13]:
# Getting CLI numpy documentation for add operation

# %run `python -c "import numpy; numpy.info(numpy.add)"`

# getting it from J notebook 
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [17]:
# Creating a numm vector of size 10 where the 7th value is 7

Z = np.zeros(10)
Z[6] = 7
print(Z)


[0. 0. 0. 0. 0. 0. 7. 0. 0. 0.]


In [58]:
Z = np.arange(10,50)

print ("Vector with values from 10 to 50")
print(Z)

from IPython import display

A = np.arange(50)
A = A[::-1]
print("")
print ("Reverse")
print(A)

Vector with values from 10 to 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reverse
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [59]:
Z = np.arange(9).reshape(3, 3)
print(Z)
#3*3 matrix

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [61]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

#shows indices of nonzero matrix

(array([0, 1, 4], dtype=int64),)


In [62]:
Z = np.eye(3)
print(Z)

#3*3 identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
Z = np.random.random((3,3,3))
print(Z)

# a 3*3 MATRIX WITH RANDOM VALUES

[[[0.70533306 0.97733201 0.78860334]
  [0.83353657 0.60205384 0.93123357]
  [0.21593576 0.28006723 0.76479449]]

 [[0.12230268 0.81857739 0.20742667]
  [0.81256591 0.49825343 0.30373743]
  [0.96943879 0.0644621  0.06484393]]

 [[0.84956925 0.0962838  0.6895295 ]
  [0.71516526 0.3871782  0.50430088]
  [0.59104234 0.45037851 0.78706166]]]


In [70]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
# minimum and maximum values of the array
#print(Z)


0.02689476165136251 0.9943418122640766


In [71]:
Z = np.random.random(30)
m = Z.mean()
print(m)

#Mean value of a rendom vetor size of 30

0.4926169201040023


### Matrix Patterns

In [74]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

#2d array having 1 on the border and 0 inside

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [77]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
print("")
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

#adding a border of 0 around an existing array

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [78]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


In [82]:
Z = np.diag(1+np.arange(4),k=1)
print(Z)

#5*5 matrix with 1234 above the diagonal
#change value of k -> -1 to bring it below the diagonal

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [84]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

#checkerboard pattern

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [86]:
print(np.unravel_index(99,(6,7,8)))
#index of the 100th element in an array of shape (6 7 8)

(1, 5, 3)


In [87]:
#tile function
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

#checkerboard pattern


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


###  Normalization

In [88]:
#Matrix normalization
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.36518439  0.06654814 -1.60987795 -0.79414815 -1.89393038]
 [ 0.77176438  0.38703666  1.11351356  0.60672901 -1.75064289]
 [ 0.77147974 -0.4222316   0.17140474  0.1235364   0.72878018]
 [ 1.18727635  1.1427076   0.69076124  0.3940816   1.07897635]
 [-1.14080115  1.51217536 -1.1105697  -0.28407672 -0.37530837]]


In [90]:
color = np.dtype([("r", np.ubyte),
("g", np.ubyte),
("b", np.ubyte),
("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### Matrix Multiplication

In [91]:
# multiply 5*3 matrix with 3*2 matrix

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [95]:
#negating elements between 3 and 8 in its index

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
